import express from 'express';
import { createServer } from 'http';
import { WebSocketServer } from 'ws';
import crypto from 'crypto';
import fs from 'fs';
import path from 'path';
const app=createServerApp();
function createServerApp(){const a=express();return a}
const server=createServer(app);
const wss=new WebSocketServer({server});
const rooms=new Map();
const PORT=Number(process.env.PORT)||10000;
app.get('/',(_,res)=>res.type('html').send(fs.readFileSync(path.join(process.cwd(),'public','index.html'),'utf8')));
app.get('/health',(_,res)=>res.json({ok:true,rooms:rooms.size}));
const id=()=>crypto.randomBytes(5).toString('hex');
const points=n=>n===55?7:n%11===0?5:n%10===0?3:n%5===0?2:1;
const deck=()=>{let a=Array.from({length:104},(_,i)=>i+1);for(let i=a.length-1;i;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
function activePlayers(r){return [...r.players.values()].filter(p=>p.status!=='waiting')}
function pub(r){return {code:r.code,host:r.host,phase:r.phase,turn:r.turn,players:[...r.players.values()].map(p=>({id:p.id,name:p.name,score:p.score,hand:p.status==='waiting'?[]:p.hand,submitted:p.status==='waiting'?false:p.submitted!==null,host:p.id===r.host,status:p.status||'playing'})),rows:r.rows,message:r.message,alert:r.alert,pending:r.pending,revealed:r.revealed||[]}}
function broadcast(r){for(let p of r.players.values())if(p.ws.readyState===1)p.ws.send(JSON.stringify({type:'state',state:pub(r)}))}
function chat(r,name,text){let s=JSON.stringify({type:'chat',name,text});for(let p of r.players.values())if(p.ws.readyState===1)p.ws.send(s)}
function start(r){let ps=activePlayers(r);if(ps.length<2)return;let d=deck();r.rows=[d.shift(),d.shift(),d.shift(),d.shift()].map(n=>[n]);for(let p of ps){p.status='playing';p.hand=d.splice(0,10).sort((a,b)=>a-b);p.score=0;p.submitted=null}r.phase='playing';r.turn=1;r.pending=null;r.resolution=[];r.revealed=[];r.message='Lượt 1/10 — chọn 1 lá bài.';r.alert=false}
function nextRound(r){r.pending=null;r.resolution=[];r.revealed=[];for(let p of activePlayers(r))p.submitted=null;if(r.turn>=10){r.phase='finished';r.message='🏁 Đã hết 10 lượt. Mỗi người đã đánh hết 10 lá.';r.alert=false;broadcast(r);return}r.turn++;r.phase='playing';r.message='Lượt '+r.turn+'/10 — chọn 1 lá bài.';r.alert=false;broadcast(r)}
const eligible=(r,c)=>r.rows.map((row,i)=>({i,last:row[row.length-1]})).filter(x=>x.last<c);
function begin(r){let ps=activePlayers(r);if(ps.length<2)return;r.phase='resolving';r.resolution=ps.map(p=>({pid:p.id,card:p.submitted})).sort((a,b)=>a.card-b.card);r.revealed=r.resolution.map(x=>({pid:x.pid,name:r.players.get(x.pid).name,card:x.card,active:false}));r.message='🔓 Tất cả lá đã tiết lộ! Lá nhỏ nhất sẽ được ghép trước.';r.alert=false;broadcast(r);setTimeout(()=>processNext(r),1200)}
function processNext(r){if(r.pending)return;if(!r.resolution.length){nextRound(r);return}let x=r.resolution.shift(),p=r.players.get(x.pid);if(!p||p.status==='waiting')return processNext(r);let c=x.card,e=eligible(r,c);r.revealed.forEach(v=>v.active=false);let rv=r.revealed.find(v=>v.pid===p.id&&v.card===c);if(rv)rv.active=true;if(!e.length){r.pending={type:'forced',player:p.id,card:c,row:null,text:p.name+' ra lá '+c+' — nhỏ hơn cả 4 hàng. Chọn một hàng để THU BÀI.'};r.message='⚠️ '+p.name+' đang xử lý lá '+c+'. Chọn một HÀNG để THU BÀI.';r.alert=true;broadcast(r);return}let row=e.reduce((a,b)=>b.last>a.last?b:a).i;if(r.rows[row].length===5){r.pending={type:'sixth',player:p.id,card:c,row,text:p.name+' ra lá '+c+' — đây là LÁ THỨ 6 của Hàng '+(row+1)+'. Bấm vào Hàng '+(row+1)+' để THU BÀI.'};r.message='🚨 LÁ THỨ 6! '+p.name+' vừa ra lá '+c+' — '+p.name+' là người THU Hàng '+(row+1)+'.';r.alert=true;broadcast(r);return}r.pending={type:'place',player:p.id,card:c,row,text:'Lá '+c+' của '+p.name+' → GỢI Ý Hàng '+(row+1)+'. Bấm vào Hàng '+(row+1)+' để ghép.'};r.message='🃏 Đến lượt '+p.name+' với lá '+c+'. Gợi ý Hàng '+(row+1)+'.';r.alert=false;broadcast(r)}
function resolveClick(r,p,row){let q=r.pending;if(!q||q.player!==p.id)return;if(q.type==='place'){if(row!==q.row||r.rows[row].length>=5)return;let c=q.card;p.hand.splice(p.hand.indexOf(c),1);r.rows[row].push(c);r.pending=null;r.message=p.name+' đã ghép lá '+c+' vào Hàng '+(row+1)+'.';r.alert=false;broadcast(r);setTimeout(()=>processNext(r),650);return}let old;if(q.type==='sixth'){if(row!==q.row)return;old=r.rows[row].slice()}else if(q.type==='forced'){if(row<0||row>3)return;old=r.rows[row].slice()}else return;let c=q.card,sc=old.reduce((s,n)=>s+points(n),0);p.hand.splice(p.hand.indexOf(c),1);p.score+=sc;r.rows[row]=[c];r.pending=null;r.message='🐮 '+p.name+' thu Hàng '+(row+1)+': '+old.join(' · ')+' = '+sc+' 🐮. Lá '+c+' là lá đầu tiên của hàng.';r.alert=q.type==='sixth';broadcast(r);setTimeout(()=>processNext(r),800)}
function uniqueName(r,n){return ![...r.players.values()].some(p=>p.name.toLowerCase()===n.toLowerCase())}
function promoteWaiting(r){for(let p of r.players.values())if(p.status==='waiting')p.status='playing'}
function leave(r,p){if(!r.players.has(p.id))return;r.players.delete(p.id);let wasPending=r.pending?.player===p.id;r.pending=null;if(r.host===p.id)r.host=r.players.keys().next().value;if(!r.players.size){rooms.delete(r.code);return}broadcast(r);chat(r,'Hệ thống',p.name+' đã rời phòng.');if(wasPending&&r.phase==='resolving')setTimeout(()=>processNext(r),150);if(r.phase==='playing'&&activePlayers(r).length&&activePlayers(r).every(x=>x.submitted!==null))setTimeout(()=>begin(r),200)}
wss.on('connection',ws=>{let room=null,p=null;ws.on('message',raw=>{let m;try{m=JSON.parse(raw)}catch{return}if(m.type==='create'||m.type==='join'){if(room)return;let name=String(m.name||'Người chơi').trim().slice(0,18)||'Người chơi';if(m.type==='create'){let code;do{code=id().slice(0,6).toUpperCase()}while(rooms.has(code));room={code,host:null,players:new Map(),phase:'lobby',turn:0,rows:[],pending:null,resolution:[],revealed:[],message:'',alert:false};rooms.set(code,room)}else{room=rooms.get(String(m.code||'').toUpperCase());if(!room)return ws.send(JSON.stringify({type:'error',message:'Không tìm thấy phòng.'}));if(room.players.size>=10)return ws.send(JSON.stringify({type:'error',message:'Phòng đã đủ 10 người.'}));}if(room.players.size>=10)return ws.send(JSON.stringify({type:'error',message:'Phòng đã đủ 10 người.'}));if(!uniqueName(room,name))return ws.send(JSON.stringify({type:'error',message:'Tên này đã có trong phòng. Mỗi người cần một tên riêng.'}));p={id:id(),name,score:0,hand:[],submitted:null,ws,status:room.phase==='lobby'||room.phase==='finished'?'playing':'waiting'};room.players.set(p.id,p);if(!room.host)room.host=p.id;ws.send(JSON.stringify({type:'hello',id:p.id}));broadcast(room);chat(room,'Hệ thống',room.phase==='lobby'||room.phase==='finished'?name+' đã vào phòng.':name+' đã vào phòng và sẽ chờ tới hết ván hiện tại.');return}if(!room||!p)return;if(m.type==='start'&&(room.phase==='lobby'||room.phase==='finished')&&activePlayers(room).length>=2){promoteWaiting(room);start(room);broadcast(room);return}if(m.type==='play'&&room.phase==='playing'&&p.status!=='waiting'&&p.submitted===null){let c=Number(m.card);if(!Number.isInteger(c)||!p.hand.includes(c))return;p.submitted=c;broadcast(room);if(activePlayers(room).every(x=>x.submitted!==null))setTimeout(()=>begin(room),250);return}if((m.type==='rowClick'||m.type==='collect')&&room.phase==='resolving'&&p.status!=='waiting'){resolveClick(room,p,Number(m.row));return}if(m.type==='chat'){let t=String(m.text||'').trim().slice(0,200);if(t)chat(room,p.name,t);return}if(m.type==='kick'){let target=room.players.get(String(m.playerId));if(!target||target.id===p.id)return;target.ws.send(JSON.stringify({type:'kicked',message:'Bạn đã bị kick khỏi phòng.'}));target.ws.close();leave(room,target);return}if(m.type==='restart'&&room.phase==='finished'){promoteWaiting(room);start(room);broadcast(room);return}});ws.on('close',()=>{if(room&&p)leave(room,p)})});server.listen(PORT,()=>console.log('6-nimmt online listening on '+PORT));