import express from 'express';
import { createServer } from 'http';
import { WebSocketServer } from 'ws';
import crypto from 'crypto';
import fs from 'fs';
import path from 'path';
const app=express(),server=createServer(app),wss=new WebSocketServer({server}),rooms=new Map(),PORT=process.env.PORT||10000;
app.get('/',(_,res)=>res.type('html').send(fs.readFileSync(path.join(process.cwd(),'public','index.html'),'utf8')));app.get('/health',(_,res)=>res.json({ok:true,rooms:rooms.size}));
const id=()=>crypto.randomBytes(5).toString('hex');const points=n=>n===55?7:n%11===0?5:n%10===0?3:n%5===0?2:1;const deck=()=>{let a=Array.from({length:104},(_,i)=>i+1);for(let i=a.length-1;i;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
function pub(r){return {code:r.code,host:r.host,phase:r.phase,turn:r.turn,players:[...r.players.values()].map(p=>({id:p.id,name:p.name,score:p.score,hand:p.hand,submitted:p.submitted!==null,host:p.id===r.host})),rows:r.rows,message:r.message,alert:r.alert,pending:r.pending,active:r.active||null,revealed:r.revealed||[]}}
function broadcast(r){let s=JSON.stringify({type:'state',state:pub(r)});for(let p of r.players.values())if(p.ws.readyState===1)p.ws.send(s)}function chat(r,name,text){let s=JSON.stringify({type:'chat',name,text});for(let p of r.players.values())if(p.ws.readyState===1)p.ws.send(s)}
function start(r){let d=deck();r.rows=[d.shift(),d.shift(),d.shift(),d.shift()].map(n=>[n]);for(let p of r.players.values()){p.hand=d.splice(0,10).sort((a,b)=>a-b);p.score=0;p.submitted=null}r.phase='playing';r.turn=1;r.pending=null;r.active=null;r.resolution=[];r.revealed=[];r.message='Lượt 1/10 — chọn 1 lá bài.';r.alert=false}
function nextRound(r){r.pending=null;r.active=null;r.resolution=[];r.revealed=[];for(let p of r.players.values())p.submitted=null;if(r.turn>=10){r.phase='finished';r.message='🏁 Đã hết 10 lượt. Mỗi người đã đánh hết 10 lá.';r.alert=false;broadcast(r);return}r.turn++;r.phase='playing';r.message='Lượt '+r.turn+'/10 — chọn 1 lá bài.';r.alert=false;broadcast(r)}
const eligible=(r,c)=>r.rows.map((row,i)=>({i,last:row[row.length-1]})).filter(x=>x.last<c);
function begin(r){r.phase='resolving';r.resolution=[...r.players.values()].map(p=>({pid:p.id,card:p.submitted})).sort((a,b)=>a.card-b.card);r.revealed=r.resolution.map(x=>({pid:x.pid,name:r.players.get(x.pid).name,card:x.card,active:false}));r.message='🔓 Tất cả lá đã tiết lộ! Đang xử lý từ lá nhỏ đến lớn…';r.alert=false;broadcast(r);setTimeout(()=>process(r),1400)}
function process(r){if(r.pending||r.active)return;if(!r.resolution.length){nextRound(r);return}let x=r.resolution.shift(),p=r.players.get(x.pid);if(!p)return process(r);let c=x.card,e=eligible(r,c),rv=r.revealed.find(v=>v.pid===p.id&&v.card===c);if(rv)rv.active=true;if(!e.length){r.pending={type:'forced',player:p.id,card:c,row:null};r.message=p.name+' đánh '+c+' — nhỏ hơn cả 4 hàng. Chọn 1 hàng để THU BÀI.';r.alert=true;broadcast(r);return}let row=e.reduce((a,b)=>b.last>a.last?b:a).i;r.active={player:p.id,card:c,row};r.message=p.name+' đánh '+c+' → gợi ý ghép Hàng '+(row+1)+'.';r.alert=false;broadcast(r);setTimeout(()=>{if(!r.active)return;let a=r.active;r.active=null;if(r.rows[a.row].length===5){r.pending={type:'sixth',player:a.player,card:a.card,row:a.row};r.message=p.name+' đánh '+a.card+' → 🚨 LÁ THỨ 6 ở Hàng '+(a.row+1)+'! '+p.name+' phải THU BÀI.';r.alert=true;broadcast(r);return}p.hand.splice(p.hand.indexOf(a.card),1);r.rows[a.row].push(a.card);r.message=p.name+' đã ghép '+a.card+' vào Hàng '+(a.row+1)+'.';broadcast(r);setTimeout(()=>process(r),650)},1000)}
function collect(r,p,row){let q=r.pending;if(!q||q.player!==p.id)return;if(q.type==='sixth'&&row!==q.row)return;if(q.type==='forced'&&(row<0||row>3))return;let old=r.rows[row].slice(),c=q.card,sc=old.reduce((s,n)=>s+points(n),0);p.hand.splice(p.hand.indexOf(c),1);p.score+=sc;r.rows[row]=[c];r.pending=null;r.message='🐮 '+p.name+' thu Hàng '+(row+1)+': '+old.join(' · ')+' = '+sc+' 🐮. Lá '+c+' là lá đầu tiên của hàng.';r.alert=true;broadcast(r);setTimeout(()=>process(r),800)}
function uniqueName(r,n){return ![...r.players.values()].some(p=>p.name.toLowerCase()===n.toLowerCase())}function leave(r,p){r.players.delete(p.id);if(r.host===p.id)r.host=r.players.keys().next().value;if(r.pending?.player===p.id)r.pending=null;if(r.active?.player===p.id)r.active=null;if(!r.players.size){rooms.delete(r.code);return}broadcast(r);chat(r,'Hệ thống',p.name+' đã rời phòng.')}
wss.on('connection',ws=>{let room=null,p=null;ws.on('message',raw=>{let m;try{m=JSON.parse(raw)}catch{return}
if(m.type==='create'||m.type==='join'){if(room)return;let name=String(m.name||'Người chơi').trim().slice(0,18)||'Người chơi';if(m.type==='create'){let code;do{code=id().slice(0,6).toUpperCase()}while(rooms.has(code));room={code,host:null,players:new Map(),phase:'lobby',turn:0,rows:[],pending:null,active:null,resolution:[],revealed:[],message:'',alert:false};rooms.set(code,room)}else{room=rooms.get(String(m.code||'').toUpperCase());if(!room)return ws.send(JSON.stringify({type:'error',message:'Không tìm thấy phòng.'}));if(room.phase!=='lobby')return ws.send(JSON.stringify({type:'error',message:'Ván đã bắt đầu.'}));if(!uniqueName(room,name))return ws.send(JSON.stringify({type:'error',message:'Tên này đã có trong phòng. Có thể bạn đang mở 2 tab — hãy đóng tab thừa.'}))}if(room.players.size>=10)return ws.send(JSON.stringify({type:'error',message:'Phòng đã đủ 10 người.'}));p={id:id(),name,score:0,hand:[],submitted:null,ws};room.players.set(p.id,p);if(!room.host)room.host=p.id;ws.send(JSON.stringify({type:'hello',id:p.id}));broadcast(room);chat(room,'Hệ thống',name+' đã vào phòng.');return}
if(!room||!p)return;if(m.type==='start'&&room.host===p.id&&room.players.size>=2&&room.phase==='lobby'){start(room);broadcast(room);return}if(m.type==='play'&&room.phase==='playing'&&p.submitted===null&&!room.pending&&!room.active){let c=Number(m.card);if(!Number.isInteger(c)||!p.hand.includes(c))return;p.submitted=c;p.message=p.name+' đã chọn bài.';broadcast(room);if([...room.players.values()].every(x=>x.submitted!==null))setTimeout(()=>begin(room),250);return}if(m.type==='collect'&&room.phase==='resolving'){collect(room,p,Number(m.row));return}if(m.type==='chat'){let t=String(m.text||'').trim().slice(0,200);if(t)chat(room,p.name,t);return}if(m.type==='kick'&&room.host===p.id){let target=room.players.get(String(m.playerId));if(!target||target.id===p.id)return;target.ws.send(JSON.stringify({type:'kicked',message:'Bạn đã bị chủ phòng kick.'}));target.ws.close();leave(room,target);return}if(m.type==='restart'&&room.phase==='finished'&&room.host===p.id){start(room);broadcast(room);return}});ws.on('close',()=>{if(room&&p&&room.players.has(p.id))leave(room,p)})});
server.listen(PORT,()=>console.log('6-nimmt online listening on '+PORT));